version: '2'
services:
  db:
    image: mysql:5.7-oracle
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: abobe_pb_db
      MYSQL_USER: abobe_pb_user
      MYSQL_PASSWORD: abobe_pb_pass
      MYSQL_ROOT_PASSWORD: db_root_pass

  my-flask-app:
    container_name: my-flask-app
    image: flask-app
    ports:
      - "5010:5000"
    restart: always
    environment:
      DB: abobe_pb_db
      DB_USERNAME: abobe_pb_user
      DB_PASSWORD: abobe_pb_pass
      HOST: db
    depends_on:
      - db

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 7000:80
    environment:
      PMA_HOST: db
